create_change_set: true
boot_disk_update: False
userData_update: False
ami_update: False
sslPolicy: ELBSecurityPolicy-2015-05
now: "{{lookup('pipe', 'date')}}"
timestamp: "{{lookup('pipe', 'date +\"%Y%m%dT%H%M%S\"')}}"
stack_name: "{{inventory_file | basename}}"
default_ssl_certificate: defaul_ssl_cert
default_ssl_arn:
cf_template_bucket: "cf-{{region}}-{{account_id}}"
subnets_count: 1
git_path: /etc/repository
ssh_key_user: ec2-user
internal_domain: "{{domain}}"
boot_disk_size:
boot_disk_type: gp2
boot_disk_update: 'false'
root_domain: "{{domain}}"
excluded_srv_records:
    - localhost
    - sam
    - instances
    - bastion
    - virtual
    - ungrouped
env_vars:
  region: "{{region | default('')}}"
  role: "{{role | lower}}"
  environment: "{{envFull | default(env)}}"
  inventory: "{{inventory_dir | basename}}"
  purpose: "{{purposeId | default(purpose) | default('')}}"
  groups: "{{group_names | join(',')}}"
ssh_key_user: ec2-user
users:
  - name: ec2-user
    ssh_keys:
      - "{{ssh_key_full | default('')}}"
allowed_instance_types:
  - a1.2xlarge
  - a1.4xlarge
  - a1.large
  - a1.medium
  - a1.xlarge
  - c4.2xlarge
  - c4.4xlarge
  - c4.8xlarge
  - c4.large
  - c4.xlarge
  - c5.2xlarge
  - c5.4xlarge
  - c5.large
  - c5.xlarge
  - c5d.2xlarge
  - c5d.4xlarge
  - c5d.large
  - c5d.xlarge
  - i3.2xlarge
  - i3.4xlarge
  - i3.large
  - i3.xlarge
  - m4.2xlarge
  - m4.4xlarge
  - m4.large
  - m4.xlarge
  - m5.2xlarge
  - m5.4xlarge
  - m5.large
  - m5.xlarge
  - m5a.2xlarge
  - m5a.4xlarge
  - m5a.large
  - m5a.xlarge
  - m5d.2xlarge
  - m5d.4xlarge
  - m5d.large
  - m5d.xlarge
  - r4.2xlarge
  - r4.4xlarge
  - r4.large
  - r4.xlarge
  - r5.2xlarge
  - r5.4xlarge
  - r5.large
  - r5.xlarge
  - r5a.2xlarge
  - r5a.4xlarge
  - r5a.large
  - r5a.xlarge
  - r5d.2xlarge
  - r5d.4xlarge
  - r5d.large
  - r5d.xlarge
  - t2.small
  - t2.medium
  - t2.large
  - t3.2xlarge
  - t3.large
  - t3.medium
  - t3.micro
  - t3.nano
  - t3.small
  - t3.xlarge