services:
  - docker
sudo: required
language: python
python:
- 3.6.5
env:
  - job=docs
  - job=package
  - job=test test=volumes
  - job=test test=bootstrap
  - job=test test=instance_volumes

script:
  - pip install awscli
  - make $job

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "*.rpm"
    - "*.deb"
  skip_cleanup: true
  on:
    tags: true