repo_url: https://github.com/moshloop/ansible-provision/
repo_name: Ansible Provision
site_name: Ansible provision
theme: material
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - codehilite:
      linenums: true


nav:
  - Getting Started: ./index.md
  - Targets:
    - AWS: ./aws.md
    - AWS Service Catalog: ./aws-service-catalog.md
    - Azure: ./azure.md
    - vmware: ./vmware.md
    - VMware Fusuion: ./vmware-fusion.md
    - VirtualBox: ./virtualbox.md
  - Volumes: ./volumes.md
  - Load Balancing: ./load-balancing.md
  - Firewalls: ./firewall.md
  - Hooks: ./hooks.md
  - Reference: ./reference.md
  - Ansible Suite:
    - ansible-extras: ./ansible-addons.md
    - ansible-run: https://www.moshloop.com/ansible-run
    - ansible-deploy: https://www.moshloop.com/ansible-deploy
    - ansible-dependencies: https://github.com/moshloop/ansible-dependencies