- debug: msg="Provisioning {{stack_name | default('') }} on {{target}}"
  run_once: true
  tags:
    - always

- name:
  file:
    path: build
    state: directory
  delegate_to: localhost
  tags:
    - always
  run_once: true

- include_vars:
    file: "{{playbook_dir}}/{{item}}"
  loop: "{{vaults | default([])}}"

- add_host:
    name: "{{inventory_hostname}}"
    groups: "{{target}},provision"
  changed_when: false
  tags:
    - always

- name: Running before (run_once) hooks {{hooks}}
  include_tasks: '{{item}}'
  vars:
    include_dir: "{{item | dirname }}"
  run_once: true
  tags:
    - always
  with_items: "{{hooks | deploy_hooks('before', True, group_names) }}"

- name: Running before hooks
  vars:
    include_dir: "{{item | dirname }}"
  include_tasks: '{{item}}'
  tags:
    - always
  with_items: "{{hooks | deploy_hooks('before', False, group_names) }}"

- include: vmware.yml
  when: target == 'vmware'
  tags:
    - always

- include: aws.yml
  when: target == 'aws' or target == 'aws-service-catalog'
  tags:
    - always

- include: azure.yml
  when: target == 'azure'
  tags:
    - always

- include_role: name="{{ role_path }}/roles/virtualbox"
  when: target == 'virtualbox'
  tags:
    - always

- include_role: name="{{ role_path }}/roles/vmware-fusion"
  when: target == 'vmware-fusion'
  tags:
    - always

- debug: msg="Provisioned  {{inventory_hostname}} -> {{ip | default('')}}"

- block:
    - file:
        path: "{{output_dir}}"
        state: directory

    - copy:
        content: "{{vm_facts}}"
        dest: "{{output_dir}}/{{inventory_hostname}}"
  when: output_dir is defined and vm_facts is defined

- name: Running after hooks
  include: '{{item}}'
  vars:
    include_dir: "{{item | dirname }}"
  with_items: "{{hooks | deploy_hooks('after', False, group_names) }}"
  tags:
    - always

- name: Running after (run_once) hooks
  vars:
    include_dir: "{{item | dirname }}"
  include: '{{item}}'
  with_items: "{{hooks | deploy_hooks('after', True, group_names) }}"
  tags:
    - always