- debug: msg="Provisioning {{stack_name | default('') }} on {{target}}"
  run_once: true

- file:
    path: build
    state: directory
  delegate_to: localhost
  tags:
    - always
  run_once: true

- name: Running before (run_once) hooks {{hooks}}
  include_tasks: '{{item}}'
  vars:
    include_dir: "{{item | dirname }}"
  run_once: true
  with_items: "{{hooks | deploy_hooks('before', True, group_names) }}"

- name: Running before hooks
  vars:
    include_dir: "{{item | dirname }}"
  include_tasks: '{{item}}'
  with_items: "{{hooks | deploy_hooks('before', False, group_names) }}"

- include: vmware.yml
  when: target == 'vmware'

- include: aws.yml
  when: target == 'aws'

- include: azure.yml
  when: target == 'azure'

- name: Running after hooks
  include: '{{item}}'
  vars:
    include_dir: "{{item | dirname }}"
  with_items: "{{hooks | deploy_hooks('after', False, group_names) }}"

- name: Running after (run_once) hooks
  vars:
    include_dir: "{{item | dirname }}"
  include: '{{item}}'
  with_items: "{{hooks | deploy_hooks('after', True, group_names) }}"