
  - set_fact:
      vcenter_login: &vcenter_login
        hostname: "{{vcenter_hostname}}"
        username: "{{vcenter_username}}"
        password: "{{vcenter_password}}"
        validate_certs: no

  - name: Finding latest template for {{template}} in "{{datacenter}}"
    vmware_guest_search:
      <<: *vcenter_login
      datacenter: "{{datacenter}}"
      name: "{{template}}"
      # name_match: last
    delegate_to: localhost
    register: vm_templates
    retries: 3
    delay: 10

  - fail:
      msg: "Template not found: {{template}}"
    when: vm_templates.vms | length == 0

  - set_fact: template_name="{{vm_templates.vms[0]}}"

  - debug: msg="Using {{vm_templates.vms[0] }}" verbosity=1

  - vmware_datastore_facts:
      <<: *vcenter_login
      datacenter: "{{datacenter}}"
      cluster: "{{cluster}}"
    delegate_to: localhost
    register: datastores
    retries: 3
    delay: 10

  - debug: var=datastores verbosity=1

  - set_fact:
      datastore: "{{datastores.datastores | selectattr('type', 'equalto', 'vsan') | first}}"

  - set_fact:
      root_volumes:
        - size_gb: "{{boot_disk_size | default(40)}}"
          type: thin
          mount: /
          datastore: "{{datastore.name}}"
      data_volumes: "{{data_volumes | default([])}}"

  - set_fact:
      data_volumes:
        - size_gb: "{{data_volume}}"
          type: thin
          mount: "{{data_volume_mount | default('/data')}}"
          datastore: "{{datastore.name}}"
      volumes:
        - size: "{{data_volume}}"
          id: VolData
          dev: /dev/sdb
          format: lvm
          mount: VolData
        - size: "{{(data_volume | int) - 1}}"
          id: VolGroup-1
          format: xfs
          owner: root
          dev: VolData
          mount: "{{data_volume_mount | default('/data')}}"
    when: data_volume is defined

  - local_action: file path="build/{{inventory_hostname}}/group_vars" state=directory

  - name: saving hostvars
    local_action: copy content="{{hostvars[inventory_hostname] | to_json}}" dest="build/{{inventory_hostname}}/group_vars/all.json"

  - name: running ansible-deploy to generate cloudinit file
    local_action: shell ansible-deploy -i {{inventory_dir}} -i build/{{inventory_hostname}} -l {{inventory_hostname}} -e target=cloudinit -c local --skip-tags slow,after_hooks,hooks
    register: cloudinit
    no_log: true
    failed_when: false

  - set_fact:
      display1: "{{cloudinit.stdout | debug_obj }}"
      display2: "{{cloudinit.stderr | debug_obj }}"

  - fail:
    when: cloudinit.rc != 0

  - set_fact:
       userData: "{{lookup('file', inventory_dir + '/build/' + inventory_hostname + '.txt') }}"
    delegate_to: localhost

  - set_fact:
      cloudinit_type: vmware
      userData: "{{userData | b64encode }}"
    when: not os is defined or os == 'vmware'

  - set_fact:
      cloudinit_type: vmware
      userData: "{{userData}}"
    when: os is defined and os == 'ubuntu'

  - set_fact:
      cloudinit_type: coreos
    when: os is defined and os == 'coreos'

  - cloudinit_iso:
      user: "{{ userData }}"
      type: "{{cloudinit_type}}"
      meta: |
        local-hostname: "{{inventory_hostname | lower}}"
      dest: /tmp/{{inventory_hostname}}.iso

  - name: "Upload cloudinit iso to: {{datacenter}}/{{datastore.name}} via {{hostname}}"
    vsphere_copy:
      host:  "{{vcenter_hostname}}"
      login:  "{{vcenter_username}}"
      password: "{{vcenter_password}}"
      src: /tmp/{{inventory_hostname}}.iso
      datacenter: "{{datacenter}}"
      datastore: "{{datastore.name}}"
      path: "/cloud-init/{{inventory_hostname}}.iso"
      validate_certs: no
    register: vsphere_copy_result
    retries: 3
    delay: 10
    until: vsphere_copy_result is not failed
    when: not ansible_check_mode

  - set_fact:
      networks:
        - vlan: "{{vlan}}"
          type: dhcp
          start_connected: True
    when: vlan is defined and vlan != ''

  - name: Configuring network via DVSwitch Name
    set_fact:
      networks:
        - name: "{{network}}"
          type: "{{ 'dhcp' if static_ip is not defined else 'static' }}"
          start_connected: True
    when: network is defined

  - name: Launching {{inventory_hostname}} on {{datacenter}}/{{cluster}} with {{template_name}} {{networks}}
    vmware_guest2:
      debug: True
      <<: *vcenter_login
      name: "{{inventory_hostname}}"
      template: "{{template_name}}"
      datacenter: "{{datacenter}}"
      datastore: "{{datastore.name}}"
      cluster: "{{cluster}}"
      folder: "{{datacenter}}/vm"
      networks: "{{networks}}"
      disk: "{{root_volumes + data_volumes}}"
      hardware:
        memory_mb: "{{(mem | default(4)) * 1024}}"
        num_cpus: "{{cpu | default(2) }}"
    register: vm
    delegate_to: localhost
    retries: 3
    delay: 10
    until: vm is not failed
    when: not ansible_check_mode

  - debug: var=vm verbosity=2

  - debug: msg="Cloned {{inventory_hostname}} -> {{vm.instance.hw_product_uuid}}"

  - name: Attach ISO
    vmware_guest2:
      <<: *vcenter_login
      uuid: "{{vm.instance.hw_product_uuid}}"
      cdrom:
        type: iso
        iso_path: "[{{datastore.name}}] cloud-init/{{inventory_hostname}}.iso"
    register: vm
    delegate_to: localhost
    retries: 3
    delay: 10
    until: vm is not failed
    when: not ansible_check_mode

  - name: Power On
    vmware_guest2:
      <<: *vcenter_login
      uuid: "{{vm.instance.hw_product_uuid}}"
      state: poweredon
    register: vm
    delegate_to: localhost
    retries: 3
    delay: 10
    until: vm is not failed
    when: not ansible_check_mode
