    - set_fact:
        vm: None
        datacenter: "{{datacenter | default(region) }}"
        cluster: "{{cluster | default(az) }}"
        template: "{{template | default(ami) }}"
        vlan: "{{ vlan | default(subnet_name) | default('') }}"
        vm_attributes: "{{vm_attributes | default(tags) | default({}) }}"
        vcenter_login: &vcenter_login
          hostname: "{{vcenter_hostname}}"
          username: "{{vcenter_username}}"
          password: "{{vcenter_password}}"
          validate_certs: no

    - name: Finding VM
      vmware_guest_facts:
        <<: *vcenter_login
        datacenter: "{{datacenter}}"
        folder: "/{{datacenter}}/vm"
        name: "{{inventory_hostname}}"
      delegate_to: localhost
      failed_when: false
      register: vm

    - debug: var=vm verbosity=1

    - debug: msg="vm does not exists"
      when: vm.instance is not defined

    - debug: msg="vm exists"
      when: vm.instance is defined

    - include_tasks: './_provision.yml'
      when: vm.instance is not defined

    - name: Waiting for IP
      vmware_guest_facts:
          <<: *vcenter_login
          datacenter: "{{datacenter}}"
          uuid: "{{vm.instance.hw_product_uuid}}"
      delegate_to: localhost
      register: vm_guest
      until: "vm_guest.instance.hw_eth0.ipaddresses != None and vm_guest.instance.hw_eth0.ipaddresses[0] != ''"
      retries: 300
      delay: 5

    - set_fact:
        ip: "{{vm_guest.instance.hw_eth0.ipaddresses[0]}}"

    - set_fact:
        vm_facts: "{{ vm_guest.instance | combine({'ip': ip})}}"

    - vmware_vm_group:
        <<: *vcenter_login
        cluster: "{{cluster}}"
        uuid: "{{vm.instance.hw_product_uuid}}"
        groups: "{{vm_groups}}"
      when: vm_groups is defined

    - vmware_guest_custom_attributes:
        <<: *vcenter_login
        uuid: "{{vm.instance.hw_product_uuid}}"
        state: present
        attributes: "{{vm_attributes | map_to_entries('name', 'value') }}"
      failed_when: false
