  - name: Gather running instances facts
    ec2_remote_facts:
      region: "{{region}}"
    register: ec2_facts
    run_once: true

  - debug: var=ec2_facts verbosity=2

  - set_fact: query="instances[?tags.Name=='{{inventory_hostname}}']"
  - set_fact: "ec2_instance={{ec2_facts| json_query(query) | first | default({}) }}"
  - debug: var=ec2_instance
  - set_fact:
      ip: "{{ec2_instance.get('private_ip_address', '')}}"
  - debug: var=ip verbosity=1