
  - cloudformation_facts:
      stack_name: "{{stack_name}}"
      region: "{{region}}"
      all_facts: true
    failed_when: false
    register: cf_facts
    check_mode: no
    run_once: true

  - set_fact:
      cf_template_existing: "{{cf_facts.ansible_facts.cloudformation.get(stack_name, {}).stack_template | default({})}}"
    run_once: true

  - set_fact:
      cf_template_existing: "{{ cf_template_existing | regex_replace('!\\w+', '') | from_yaml}}"
    run_once: true

  - debug: var=cf_template_existing verbosity=2
    run_once: true

  - set_fact:
      cf_properties: {}
      block_device_mapping: []

  - ec2_vol_facts:
      region: "{{region}}"
      filters:
        volume-id: "{{ (ec2_instance.block_device_mapping  | selectattr('device_name', 'equalto', '/dev/sda1') | first).volume_id }}"
    register: boot_disk
    check_mode: no
    when: ec2_instance is defined and not ( boot_disk_update | bool)

  - debug: var=boot_disk verbosity=1
    when: boot_disk is defined

  - debug: var=cf_template_existing

  - name: Lookup existing cloudformation template
    set_fact:
      cf_properties: "{{ (cf_template_existing | from_yaml | default({})).get('Resources', {}).get(inventory_hostname, {})['Properties'] | default({})}}"

  - set_fact:
      cf_properties: {}
    when: cf_properties is not defined

  - debug: var=cf_properties

  - name: Saving boot device mappings
    set_fact:
      block_device_mapping: "{{ cf_properties.get('BlockDeviceMappings', []) }}"

  - name: Reusing boot disk size to prevent re-creation
    set_fact:
      boot_disk_size: "{{ block_device_mapping[0].Ebs.VolumeSize }}"
      boot_disk_type: "{{ block_device_mapping[0].Ebs.VolumeType | default('standard') }}"
    when: not boot_disk_update | bool and block_device_mapping | length > 0
    delegate_to: localhost

  - block:
        - debug: msg="Looking up existing user data definition to reuse"
        - ec2_instance_attribute_facts:
            instance_id: "{{ec2_instance.id}}"
            attribute: "userData"
            region: "{{region}}"
          register: userDataFact
        - set_fact: userData="{{userDataFact.attributes.UserData.Value}}"
    when: ec2_instance is defined and not userData_update | bool
    delegate_to: localhost