  - name: install fireviz
    shell: mkdir -p .bin && wget -nv -O ./.bin/fireviz https://github.com/moshloop/fireviz/releases/download/1.3/fireviz && chmod +x ./.bin/fireviz
    creates: ./.bin/fireviz

  - name: render security groups
    shell: "mkdir -p build && ./.bin/fireviz export firewall/*.gv --cloudformation --vpc {{vpc}} --mapping firewall/mapping.yml > build/fw.cf"
    register: fireviz

  - debug: var=fireviz.stderr

  - name: Create cloudformation S3 bucket
    aws_s3:
      bucket: "{{cf_template_bucket}}"
      region: "{{region}}"
      mode: create
    when: not ansible_check_mode
    delegate_to: localhost

  - name: upload cloudformation to S3
    aws_s3:
      bucket: "{{cf_template_bucket}}"
      object: "{{timestamp}}-fw.cf"
      region: "{{region}}"
      src: build/fw.cf
      mode: put
    register: url
    when: not ansible_check_mode
    delegate_to: localhost

  - name: deploy security groups
    cloudformation:
      stack_name: "securitygroups"
      create_changeset: true
      state: "present"
      region: "{{region}}"
      template_url: "{{url.url}}"
    when: not ansible_check_mode