  - name: checking existing certicates
    run_once: true
    tags: always
    iam_server_certificate_facts:
      name: "{{default_ssl_certificate}}"
    register: server_cert

  - name: generating self signed certificate
    shell: "/usr/bin/openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/C=US/L=JHB/O=Dis/CN=test.com' -out /tmp/cert -keyout /tmp/cert.key"
    run_once: true
    delegate_to: localhost
    when:  server_cert.results | length == 0

  - name: uploading self signed certificate
    run_once: true
    iam_cert:
      name: "{{default_ssl_certificate}}"
      state: present
      cert: "{{ lookup('file', '/tmp/cert') }}"
      key: "{{ lookup('file', '/tmp/cert.key') }}"
      cert_chain: "{{ lookup('file', '/tmp/cert') }}"
    register: uploaded_cert
    failed_when: false
    when:  server_cert.results | length == 0

  # - set_fact: default_ssl_arn="{{uploaded_cert.arn}}"
  #   failed_when: false
  #   run_once: true
  #   when:  server_cert.results | length == 0

  # - set_fact: default_ssl_arn="{{server_cert.results[default_ssl_certificate].arn}}"
  #   failed_when: false
  #   run_once: true
  #   when:  server_cert.results | length >= 1
