  - set_fact: debug=false
    when: debug is not defined

  - file:
      path: build
      state: directory
    run_once: true

  - name: Global lookups
    import_tasks: lookups.yml
    run_once: true
    tags: always

  - name:  deploy security groups
    import_tasks: firewall.yml
    when: "'firewall' | dir_exists"
    tags:
      - fw

  - name: deploy misc cloudformation
    include_tasks: 'misc-cloudformation.yml'
    with_fileglob:
      - "cloudformation/*"
    tags:
      - misc

  - meta: end_play
    tags:
      - misc


  - name: Gather running instances facts
    ec2_remote_facts:
      region: "{{region}}"
    register: ec2_facts
    run_once: true
    tags: instances

  - set_fact: deploy_elb=true
    tags:
      - elb


  - include_tasks: generateCert.yml
    run_once: true
    tags:
      - elb

  - name: deploy instances
    import_tasks: instances.yml
    tags:
      - instances

  - debug: var=groups['all']
    run_once: true
    tags:
      - inventory

  - file: path=docs state=directory
    run_once: true
    tags:
      - inventory

  - name: render inventory table
    template: src=inventory.md.tpl dest=docs/{{stack_name | upper}}.md
    run_once: true
    tags:
      - inventory