  - set_fact: debug=false
    when: debug is not defined
  - set_fact: fw=false
    when: fw is not defined
  - set_fact: misc=false
    when: misc is not defined
  - set_fact: elb=true
    when: elb is not defined
  - set_fact: dns=true
    when: dns is not defined

  - debug: msg="misc={{misc}}, fw={{fw}}, elb={{elb}}, dns={{dns}}"
    run_once: true

  - file:
      path: build
      state: directory
    run_once: true

  - name: Global lookups
    import_tasks: lookups.yml
    run_once: true
    tags: always

  - block:
      - debug:
          msg: "Deploying security groups: {{'firewall' | dir_exists}}"
      - name:  deploy security groups
        include_tasks: firewall.yml
    when: fw
    run_once: true

  - block:
      - debug:
          msg: "Deploying cloudformation"
      - name: deploy {{item}} cloudformation
        include_tasks: misc-cloudformation.yml
        with_fileglob:
          - "cloudformation/*"
    when: misc
    run_once: true


  - meta: end_play
    when: misc or fw

  - name: Gather running instances facts
    ec2_remote_facts:
      region: "{{region}}"
    register: ec2_facts
    run_once: true
    tags: instances

  - include_tasks: generateCert.yml
    run_once: true
    tags:
      - elb

  - name: deploy instances
    import_tasks: instances.yml
    tags:
      - instances

  - debug: var=groups['all']
    run_once: true
    tags:
      - inventory

  - file: path=docs state=directory
    run_once: true
    tags:
      - inventory

  - name: render inventory table
    template: src=inventory.md.tpl dest=docs/{{stack_name | upper}}.md
    run_once: true
    tags:
      - inventory