  - name: render cloudformation template for {{item}}
    template: src="{{item}}" dest="build/{{item | basename}}"

  - name: deploy custom cloudformation
    cloudformation:
      stack_name: "{{ (item | basename  | splitext)[0] }}"
      create_changeset: "{{create_change_set}}"
      state: "present"
      region: "{{region}}"
      template: "build/{{item | basename}}"
    when: not ansible_check_mode
