  - include: ../volumes.yml
  - include: ../cloud-init.yml

  - name: Clone VM (Linked)
    shell: VBoxManage clonevm {{template}} --register --options link --name {{inventory_hostname}} --snapshot {{snapshot_name}}
    when: clone_type == 'link'

  - name: Clone VM (Full)
    shell: VBoxManage clonevm {{template}} --register --name {{inventory_hostname}}
    when: clone_type == '' or clone_type == 'full'

  - name: Configure Host only Network
    shell: VBoxManage modifyvm {{inventory_hostname}} --nic1 hostonly --hostonlyadapter1 {{network | split(':') | last}}
    when: network.startswith('hostonly')

  - name: Configure NAT Network
    shell: VBoxManage modifyvm {{inventory_hostname}} --nic1 natnetwork --nat-network1 {{network | split (':') | last}} --macaddress1 auto
    when: network.startswith('natnetwork')

  - name: Configure Internal Network
    shell: VBoxManage modifyvm {{inventory_hostname}} --nic1 intnet --macaddress1 auto
    when: network.startswith('intnet')

  - name: Attach ISO
    shell: VBoxManage storageattach {{inventory_hostname}} --storagectl "IDE" --port 0 --device 0 --type dvddrive --medium /tmp/{{inventory_hostname}}.iso

  - name: Power On
    shell: VBoxManage startvm {{inventory_hostname}}

  # have not found a reliable way to get ip address yet
  - set_fact:
      ip: ""
      vm_facts:
        ip: ""
